accounts/urls.py
from django.conf.urls import url
from .views import *

app_name = 'account'

urlpatterns = [

    url(r'^login/$', login_view, name='login'),

    url(r'^newuser/$', user_view, name='newuser'),

    url(r'^logout/$', logout_view, name="logout"),

    url(r'^password/$', change_password, name='Change Password'),

]

src/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_view, name='home'),
    url(r'^userprofile/', include('userprofile.urls')),
    url(r'^accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.conf.urls import url
from .views import *

app_name = 'app'

urlpatterns = [

    ######################################################################
    url(r'^home/$', company_view, name='homeC'),
    ######################################################################

    ######################################################################
    url(r'^homeCustomer/$', customer_view, name='homeCu'),
    ######################################################################

    ######################################################################
    url(r'^homeAdmin/$', admin_view, name='homeA'),
    ######################################################################

    ######################################################################
    url(r'^settings/$', setting_view, name='settings'),
    ######################################################################

    ######################################################################
    url(r'^companys/$', company_index, name='indexC'),
    url(r'^(?P<c_id>\d+)/detailCompany/$', company_detail, name='detailCompany'),
    url(r'^(?P<c_id>\d+)/updateCompany/$', company_update, name='updateCompany'),
    url(r'^(?P<c_id>\d+)/deleteCompany/$', company_delete, name='deleteCompany'),
    ######################################################################

    ######################################################################
    url(r'^employees/$', employee_index, name='index'),
    url(r'^employee/add/$', employee_create, name='create'),
    url(r'^(?P<e_slug>[\w-]+)/detail/$', employee_detail, name='detail'),
    url(r'^(?P<e_slug>[\w-]+)/update/$', employee_update, name='update'),
    url(r'^(?P<e_slug>[\w-]+)/delete/$', employee_delete, name='delete'),
    ######################################################################

    ######################################################################
    url(r'^heads/$', head_index, name='indexH'),
    ######################################################################

    ######################################################################
    url(r'^others/$', other_index, name='indexO'),
    ######################################################################

    ######################################################################
    url(r'^companyuser/$', companyuser_index, name='companyuser'),
    ######################################################################

    ######################################################################
    url(r'^companyuser2/$', companyuser2_index, name='companyuser2'),
    ######################################################################

    ######################################################################
    url(r'^customeruser/$', customeruser_index, name='customeruser'),
    ######################################################################

    ######################################################################
    url(r'^departments/$', department_index, name='indexD'),
    url(r'^department/add/$', department_create, name='createD'),
    url(r'^(?P<d_slug>[\w-]+)/detailD/$', department_detail, name='detailD'),
    url(r'^(?P<d_slug>[\w-]+)/updateD/$', department_update, name='updateD'),
    url(r'^(?P<d_slug>[\w-]+)/deleteD/$', department_delete, name='deleteD'),
    #######################################################################

    #######################################################################
    url(r'^projects/$', project_index, name='indexP'),
    url(r'^project/add/$', project_create, name='createP'),
    url(r'^(?P<p_slug>[\w-]+)/detailP/$', project_detail, name='detailP'),
    url(r'^(?P<p_slug>[\w-]+)/updateP/$', project_update, name='updateP'),
    url(r'^(?P<p_slug>[\w-]+)/deleteP/$', project_delete, name='deleteP'),
    url(r'^projectP/$', projectC_index, name='projectP'),
    url(r'^(?P<p_slug>[\w-]+)/deletePC/$', projectC_delete, name='deletePC'),
    #######################################################################

    #######################################################################
    url(r'^issues/$', issue_index, name='indexI'),
    url(r'^issue/add/$', issue_create, name='createI'),
    url(r'^(?P<id>\d+)/detailI/$', issue_detail, name='detailI'),
    url(r'^(?P<id>\d+)/updateI/$', issue_update, name='updateI'),
    url(r'^(?P<id>\d+)/deleteI/$', issue_delete, name='deleteI'),
    #######################################################################

    #######################################################################
    url(r'^subtasks/$', subtask_index, name='indexSub'),
    url(r'^subtask/add/$', subtask_create, name='createSub'),
    url(r'^(?P<id>\d+)/detailSub/$', subtask_detail, name='detailSub'),
    url(r'^(?P<id>\d+)/updateSub/$', subtask_update, name='updateSub'),
    url(r'^(?P<id>\d+)/deleteSub/$', subtask_delete, name='deleteSub'),
    #######################################################################

    #######################################################################
    url(r'^workflows/$', workflow_index, name='indexW'),
    url(r'^workflow/add/$', workflow_create, name='createW'),
    url(r'^(?P<id>\d+)/detailW/$', workflow_detail, name='detailW'),
    url(r'^(?P<id>\d+)/updateW/$', workflow_update, name='updateW'),
    url(r'^(?P<id>\d+)/deleteW/$', workflow_delete, name='deleteW'),
    #######################################################################

    #######################################################################
    url(r'^plans/$', plan_index, name='indexPlan'),
    url(r'^plan/add/$', plan_create, name='createPlan'),
    url(r'^(?P<id>\d+)/detailPlan/$', plan_detail, name='detailPlan'),
    url(r'^(?P<id>\d+)/updatePlan/$', plan_update, name='updatePlan'),
    url(r'^(?P<id>\d+)/deletePlan/$', plan_delete, name='deletePlan'),
    #######################################################################
]

templates/base.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Project Administration System{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
     <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body background="media/pic7.jpg">
        {% include 'header.html' %}
        {% include 'messages.html' %}

        {% block body %}

        {% endblock %}

        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/header.html
<!-- Navbar Start -->
{% load register %}
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand" style="color: white">Project Administration System</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            {% if request.user.is_authenticated %}
                <form class="navbar-form navbar-left" role="search" method="GET" action="">
                    <div class="input-group">
                        <input class="form-control" type="text" name="q" placeholder="Search on system" value="" >
                        <span class="input-group-btn">
                            <input class="btn btn-default" type="submit" value="Search">
                        </span>
                    </div>
                </form>
            {% endif %}

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'home' %}" style="color: white">Home</a></li>
                    <li><a href="{% url 'account:login' %}" style="color: white">Sign In</a></li>
                {% endif %}
                {% if request.user.is_authenticated %}
                     {% if request.user.is_superuser %}
                        <li><a href="{% url 'app:homeA' %}" style="color: white">Home</a></li>
                        <li><a href="{% url 'app:indexC' %}" style="color: white">User</a></li>
                        <li><a href="{% url 'account:newuser' %}" style="color: white">Create User</a></li>
                        <li><a href="{% url 'app:settings' %}" style="color: white">Settings</a></li>
                        <li><a href="{% url 'account:logout' %}" style="color: white">Sign Out</a></li>
                    {% else %}
                        {% if request.user|is_group:"companys" %}
                            <li><a href="{% url 'app:homeC' %}" style="color: white">Home</a></li>
                            <li><a href="{% url 'app:indexD' %}" style="color: white">Department</a></li>
                            <li><a href="{% url 'app:index' %}" style="color: white">Employee</a></li>
                            <li><a href="{% url 'app:indexP' %}" style="color: white">Project</a></li>
                            <li><a href="{% url 'app:indexW' %}" style="color: white">Workflow</a></li>
                            <li><a href="{% url 'app:settings' %}" style="color: white">Settings</a></li>
                            <li><a href="{% url 'account:logout' %}" style="color: white">Sign Out</a></li>
                        {% endif %}
                        {% if request.user|is_group:"customers" %}
                            <li><a href="{% url 'app:homeCu' %}" style="color: white">Home</a></li>
                            <li><a href="{% url 'app:companyuser2' %}" style="color: white">Company</a></li>
                            <li><a href="{% url 'app:projectP' %}" style="color: white">Project</a></li>
                            <li><a href="{% url 'app:settings' %}" style="color: white">Settings</a></li>
                            <li><a href="{% url 'account:logout' %}" style="color: white">Sign Out</a></li>
                        {% endif %}
                    {% endif %}
                {% endif %}
                <!-- <li><a href="#">Customer</a></li> --->
            </ul>

        </nav>

    </div>
</nav>

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}