src/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import home_view
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_view, name='home'),
    url(r'^userprofile/', include('userprofile.urls')),
    url(r'^accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userprofile/urls.py
from django.conf.urls import url
from .views import *

app_name = 'app'

urlpatterns = [

    ######################################################################
    url(r'^home/$', company_view, name='homeC'),
    ######################################################################

    ######################################################################
    url(r'^homeCustomer/$', customer_view, name='homeCu'),
    ######################################################################

    ######################################################################
    url(r'^homeAdmin/$', admin_view, name='homeA'),
    ######################################################################

    ######################################################################
    url(r'^settings/$', setting_view, name='settings'),
    ######################################################################

    ######################################################################
    url(r'^companys/$', company_index, name='indexC'),
    url(r'^(?P<c_id>\d+)/detailCompany/$', company_detail, name='detailCompany'),
    url(r'^(?P<c_id>\d+)/updateCompany/$', company_update, name='updateCompany'),
    url(r'^(?P<c_id>\d+)/deleteCompany/$', company_delete, name='deleteCompany'),
    ######################################################################

    ######################################################################
    url(r'^employees/$', employee_index, name='index'),
    url(r'^employee/add/$', employee_create, name='create'),
    url(r'^(?P<e_slug>[\w-]+)/detail/$', employee_detail, name='detail'),
    url(r'^(?P<e_slug>[\w-]+)/update/$', employee_update, name='update'),
    url(r'^(?P<e_slug>[\w-]+)/delete/$', employee_delete, name='delete'),
    ######################################################################

    ######################################################################
    url(r'^heads/$', head_index, name='indexH'),
    ######################################################################

    ######################################################################
    url(r'^others/$', other_index, name='indexO'),
    ######################################################################

    ######################################################################
    url(r'^companyuser/$', companyuser_index, name='companyuser'),
    ######################################################################

    ######################################################################
    url(r'^companyuser2/$', companyuser2_index, name='companyuser2'),
    ######################################################################

    ######################################################################
    url(r'^customeruser/$', customeruser_index, name='customeruser'),
    ######################################################################

    ######################################################################
    url(r'^departments/$', department_index, name='indexD'),
    url(r'^department/add/$', department_create, name='createD'),
    url(r'^(?P<d_slug>[\w-]+)/detailD/$', department_detail, name='detailD'),
    url(r'^(?P<d_slug>[\w-]+)/updateD/$', department_update, name='updateD'),
    url(r'^(?P<d_slug>[\w-]+)/deleteD/$', department_delete, name='deleteD'),
    #######################################################################

    #######################################################################
    url(r'^projects/$', project_index, name='indexP'),
    url(r'^project/add/$', project_create, name='createP'),
    url(r'^(?P<p_slug>[\w-]+)/detailP/$', project_detail, name='detailP'),
    url(r'^(?P<p_slug>[\w-]+)/updateP/$', project_update, name='updateP'),
    url(r'^(?P<p_slug>[\w-]+)/deleteP/$', project_delete, name='deleteP'),
    url(r'^projectP/$', projectC_index, name='projectP'),
    url(r'^(?P<p_slug>[\w-]+)/deletePC/$', projectC_delete, name='deletePC'),
    #######################################################################

    #######################################################################
    url(r'^issues/$', issue_index, name='indexI'),
    url(r'^issue/add/$', issue_create, name='createI'),
    url(r'^(?P<id>\d+)/detailI/$', issue_detail, name='detailI'),
    url(r'^(?P<id>\d+)/updateI/$', issue_update, name='updateI'),
    url(r'^(?P<id>\d+)/deleteI/$', issue_delete, name='deleteI'),
    #######################################################################

    #######################################################################
    url(r'^subtasks/$', subtask_index, name='indexSub'),
    url(r'^subtask/add/$', subtask_create, name='createSub'),
    url(r'^(?P<id>\d+)/detailSub/$', subtask_detail, name='detailSub'),
    url(r'^(?P<id>\d+)/updateSub/$', subtask_update, name='updateSub'),
    url(r'^(?P<id>\d+)/deleteSub/$', subtask_delete, name='deleteSub'),
    #######################################################################

    #######################################################################
    url(r'^workflows/$', workflow_index, name='indexW'),
    url(r'^workflow/add/$', workflow_create, name='createW'),
    url(r'^(?P<id>\d+)/detailW/$', workflow_detail, name='detailW'),
    url(r'^(?P<id>\d+)/updateW/$', workflow_update, name='updateW'),
    url(r'^(?P<id>\d+)/deleteW/$', workflow_delete, name='deleteW'),
    #######################################################################

    #######################################################################
    url(r'^plans/$', plan_index, name='indexPlan'),
    url(r'^plan/add/$', plan_create, name='createPlan'),
    url(r'^(?P<id>\d+)/detailPlan/$', plan_detail, name='detailPlan'),
    url(r'^(?P<id>\d+)/updatePlan/$', plan_update, name='updatePlan'),
    url(r'^(?P<id>\d+)/deletePlan/$', plan_delete, name='deletePlan'),
    #######################################################################
]

templates/project/detail.html
{% extends 'base.html' %}

{% block body %}

    <div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="thumbnail">
                <div class="caption">
                    {%if project.image %}
                        <img src="{{ project.image.url }}" class="img-responsive">
                    {% endif %}
                    <h3>{{ project.p_title }}</h3>
                    <p>ID: {{ project.p_id }}</p>
                    <p>Start Date: {{ project.p_startdate }}</p>
                    <p>End Date: {{ project.p_enddate}}</p>
                    <p>Situation {{ project.p_situation }}</p>
                    <p>Company: {{ project.cProject }}</p>
                    <p>Department: {{ project.dProject }}</p>
                    <p>Project Manager: {{ project.eProject }}</p>
                    <p>
                        <a href="{{ project.get_updateP_url }}" class="btn btn-default" role="button">Update</a>
                        <a href="{{ project.get_deleteP_url }}" class="btn btn-danger" role="button">Delete</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/project/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="container">
         <div class="row">
             <div class="col-md-6 col-md-offset-3">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                     <h1>Project</h1>
                     {{ form|crispy }}
                     {{ form.media }}
                     <input type="submit" value="Add">
                 </form>
             </div>
         </div>
    </div>


{% endblock %}

templates/project/index.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <p> <a href="{% url 'app:createP' %}" class="btn btn-primary" role="button">New Project Add</a>
            <a href="{% url 'app:indexI' %}" class="btn btn-primary" role="button">Issues of Projects</a>
            <a href="{% url 'app:indexPlan' %}" class="btn btn-primary" role="button">Projects Plan</a>
        </p>
    {% for project in projects %}
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>{{ project.p_title }}</h3>
                        <p>Company: {{ project.cProject }}</p>
                        <p><a href="{{ project.get_project_url }}" class="btn btn-primary" role="button">Research</a>
                            <a href="{{ project.get_updateP_url }}" class="btn btn-default" role="button">Update</a>
                            <a href="{{ project.get_deleteP_url }}" class="btn btn-danger" role="button">Delete</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
     <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="pagination">
                <span class="step-links">
                    {% if projects.has_previous %}
                        <a href="?page={{ projects.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="current">
                        Page {{ projects.number }} of {{ projects.paginator.num_pages }}.
                    </span>

                    {% if projects.has_next %}
                        <a href="?page={{ projects.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/project/projectC.html
{% extends 'base.html' %}

{% block body %}
    <div class="container">
        <p><a href="{% url 'app:createP' %}" class="btn btn-primary" role="button">New Project Request</a></p>
    {% for project in projects %}
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>{{ project.p_title }}</h3>
                        <p>Company: {{ project.cProject }}</p>
                        <p><a href="{{ project.get_project_url }}" class="btn btn-primary" role="button">Research</a>
                            <a href="{{ project.get_deletePC_url }}" class="btn btn-primary" role="button">Buy</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
     <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="pagination">
                <span class="step-links">
                    {% if projects.has_previous %}
                        <a href="?page={{ projects.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="current">
                        Page {{ projects.number }} of {{ projects.paginator.num_pages }}.
                    </span>

                    {% if projects.has_next %}
                        <a href="?page={{ projects.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

templates/project/update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block body %}
    <div class="container">
         <div class="row">
             <div class="col-md-6 col-md-offset-3">
                 <form method="POST">
                    {% csrf_token %}
                    <h1>Update Project</h1>
                    {{ form|crispy }}
                    <input class="btn btn-primary" type="submit" value="Update">
                </form>
             </div>
         </div>
    </div>


{% endblock %}